### ISSUE TITLE
Grunt error

### ISSUE THREAD

**Issue by tnunamak** [CaryLandholt/AngularFun#1]
I'm new to all of this but wanted to let you know I hit an error following the very direct instructions on the grunt step:

```
tnunamak$ grunt bootstrap
Running "delete:dist" (delete) task

Running "coffeeLint:scripts" (coffeeLint) task

Running "copy:dist" (copy) task

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
TypeError: Object #<Object> has no method 'existsSync'
    at Object.<anonymous> (/Users/tnunamak/workspace/AngularFun/build/tasks/copy.js:17:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/lib/grunt/task.js:103:15)
    at Object.<anonymous> (/usr/local/lib/node_modules/grunt/lib/grunt/task.js:56:16)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:341:36)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:317:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:344:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:317:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:344:11)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:317:9)
    at Task.<anonymous> (/usr/local/lib/node_modules/grunt/lib/util/task.js:344:11)
```

**Comment by CaryLandholt** [comment]
Try updating [Node.js](http://nodejs.org/) to the latest version (v0.81).
I noticed some issues prior to the upgrade.

Also, I've made some significant changes in the last few hours.  Unless you've also made changes, you should go ahead and pull the latest.

Please let me know if you're still having trouble.  Thanks

**Comment by CaryLandholt** [comment]
I just verified on both Mac OS X Lion and Windows 7 with Node.js v0.8.1 everything seems to be working.
I did this with new repo clones.

**Comment by tnunamak** [comment]
Me too. I upgraded everything and it worked. I think I might have had an environment issue. Thanks a bunch!

**Comment by CaryLandholt** [comment]
Glad to hear - thanks!
