### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by pkrnjevic** [CaryLandholt/AngularFun#35]
Not sure if I'm doing something wrong, but this is what happens when I run "grunt tests":

```
Running "testacular:unit" (testacular) task
[2013-04-09 17:25:07.724] [DEBUG] config - autoWatch set to false, because of singleRun
INFO [testacular]: Testacular server started at http://localhost:8081/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 27.0 (Mac)]: Connected on socket id 4LMsNDduoNvuzdQZsCIr
Chrome 27.0 (Mac) person service should query for people at /people and receive an array FAILED
    Error: No pending request to flush !
    at Error (<anonymous>)
    at Function.$httpBackend.flush (/Users/peterk/angularjs/AngularFun/test/scripts/libs/angular-mocks.js:1148:34)
        at null.<anonymous>  (/Users/peterk/angularjs/AngularFun/dist_test/scripts/services/personSpec.js:39:25)
Chrome 27.0 (Mac): Executed 2 of 2 (1 FAILED) (0.145 secs / 0.034 secs)
Warning: Task "testacular:unit" failed. Use --force to continue.

Aborted due to warnings.
air11:AngularFun peterk$ 
```

**Comment by CaryLandholt** [comment]
Yep - I'm getting that error too.  I'm looking into it.

**Comment by CaryLandholt** [comment]
@pkrnjevic,

The tests should now pass.  The httpBackend was being flushed but no backend was available to flush.  :)

Please let me know if you're good.

Thanks,
Cary

**Comment by pkrnjevic** [comment]
Hi Cary,

That fixed it perfectly! Runs nicely now.

Thanks,
Peter

**Comment by CaryLandholt** [comment]
Cool - closing the issue.
