### ISSUE TITLE
npm install script not working in Windows

### ISSUE THREAD

**Issue by CaryLandholt** [CaryLandholt/AngularFun#53]
Could be a path escaping problem.

**Comment by CaryLandholt** [comment]
Added bower install to README in the meantime

**Comment by makc** [comment]
does not work for me on mac osx 10.8.5, too

```
...
npm http 304 https://registry.npmjs.org/growl
npm http 304 https://registry.npmjs.org/jade/0.26.3
unbuild jpegtran-bin@0.2.0
npm ERR! Error: EMFILE, open '/Users/makc/IdeaProjects/AngularFun/node_modules/grunt-coffeelint/node_modules/coffeelint/node_modules/coffee-script/extras/jsl.conf'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"

/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:266
  log.error("cwd", process.cwd())
                           ^
Error: EMFILE, too many open files
    at process.errorHandler (/usr/local/lib/node_modules/npm/lib/utils/error-handler.js:266:28)
    at process.EventEmitter.emit (events.js:117:20)
    at process._fatalException (node.js:272:26)
```

**Comment by CaryLandholt** [comment]
@makc - can you verify if it still isn't working?
Sometimes the npm service is down.

Thanks,
Cary

**Comment by CaryLandholt** [comment]
Can you try again with the latest code?

**Comment by makc** [comment]
still getting loads of errors, e.g.

```
npm http 200 https://registry.npmjs.org/inquirer/-/inquirer-0.2.5.tgz
npm http 200 https://registry.npmjs.org/async
unbuild grunt-contrib-imagemin@0.4.0
npm ERR! Error: ENOENT, chown '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/chalk/readme.md'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/makc/IdeaProjects/colt/angularfun/AngularFun
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/chalk/readme.md
npm ERR! fstream_path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/chalk/readme.md
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! fstream_finish_call chown
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:305:19
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:265:7
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! error rolling back Error: ENOTEMPTY, rmdir '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/filesize'
npm ERR! error rolling back  grunt-contrib-imagemin@0.4.0 { [Error: ENOTEMPTY, rmdir '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/filesize']
npm ERR! error rolling back   errno: 53,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   path: '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/filesize' }
npm ERR! Error: ENOENT, open '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/async/package.json'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/makc/IdeaProjects/colt/angularfun/AngularFun
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/async/package.json
npm ERR! code ENOENT
npm ERR! errno 34
npm http 304 https://registry.npmjs.org/dateformat/1.0.2-1.2.3
npm ERR! Error: ENOENT, lstat '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin/lib/pngquant.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/makc/IdeaProjects/colt/angularfun/AngularFun
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin/lib/pngquant.js
npm ERR! fstream_path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin/lib/pngquant.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/lib/gifsicle.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/makc/IdeaProjects/colt/angularfun/AngularFun
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/lib/gifsicle.js
npm ERR! fstream_path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/gifsicle/lib/gifsicle.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/optipng-bin/lib/optipng.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 12.5.0
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/makc/IdeaProjects/colt/angularfun/AngularFun
npm ERR! node -v v0.10.13
npm ERR! npm -v 1.3.2
npm ERR! path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/optipng-bin/lib/optipng.js
npm ERR! fstream_path /Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/optipng-bin/lib/optipng.js
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/local/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! Error: ENOENT, lstat '/Users/makc/IdeaProjects/colt/angularfun/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/jpegtran-bin/lib/jpegtran.js'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>
```

**Comment by CaryLandholt** [comment]
Install karma globally on Windows.
`npm install -g karma`
