### ISSUE TITLE
issues running after using jslove

### ISSUE THREAD

**Issue by beninfobelt** [CaryLandholt/AngularFun#55]
I started to look into getting AngularFun up and running with jslove

It converted from the coffee script well with no errors but I am having issues with grunt. I did perform the npm install and the bower install before running grunt jslove.

Now when I run the grunt command I get this error:

Running "clean:working" (clean) task
Cleaning ./.temp/...OK

Running "coffeelint:scripts" (coffeelint) task

> > 0 files lint free.

Running "copy:app" (copy) task
Created 10 directories, copied 22 files

Running "ngShim:scripts" (ngShim) task

> > Source file " ./.temp/scripts/libs/angular-animate.min.js" not found.
> > Source file " ./.temp/scripts/libs/angular-resource.min.js" not found.
> > Source file " ./.temp/scripts/libs/angular-route.min.js" not found.

Running "coffee:app" (coffee) task
File .temp/scripts/app.js created.
File .temp/scripts/app.js.map created.
File .temp/scripts/bootstrap.js created.
File .temp/scripts/bootstrap.js.map created.
File .temp/scripts/main.js created.
File .temp/scripts/main.js.map created.

Running "less:app" (less) task

> > FileError: 'bootstrap.less' wasn't found in ./.temp/styles/styles.less on line 1, column 1:
> > 1 @import "bootstrap.less";
> > 2
> > Warning: Error compiling LESS. Use --force to continue.

Aborted due to warnings.

When I run the grunt sever command, the browser page loads but I get this error in the chrome tab:

Error: Cannot find module 'html'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:274:25)
    at Module.require (module.js:358:17)
    at require (module.js:374:17)
    at new View (/home/benjamin/workspace/AngularFun/node_modules/express/lib/view.js:43:49)
    at Function.app.render (/home/benjamin/workspace/AngularFun/node_modules/express/lib/application.js:488:12)
    at ServerResponse.res.render (/home/benjamin/workspace/AngularFun/node_modules/express/lib/response.js:760:7)
    at /home/benjamin/workspace/AngularFun/routes.js:35:18
    at callbacks (/home/benjamin/workspace/AngularFun/node_modules/express/lib/router/index.js:164:37)
    at param (/home/benjamin/workspace/AngularFun/node_modules/express/lib/router/index.js:138:11)
    at pass (/home/benjamin/workspace/AngularFun/node_modules/express/lib/router/index.js:145:5)
    at Router._dispatch (/home/benjamin/workspace/AngularFun/node_modules/express/lib/router/index.js:173:5)
    at Object.router (/home/benjamin/workspace/AngularFun/node_modules/express/lib/router/index.js:33:10)
    at next (/home/benjamin/workspace/AngularFun/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at resume (/home/benjamin/workspace/AngularFun/node_modules/express/node_modules/connect/lib/middleware/static.js:60:7)
    at SendStream.error (/home/benjamin/workspace/AngularFun/node_modules/express/node_modules/connect/lib/middleware/static.js:73:37)
    at SendStream.EventEmitter.emit (events.js:100:17)
    at SendStream.error (/home/benjamin/workspace/AngularFun/node_modules/express/node_modules/send/lib/send.js:147:51)
    at SendStream.onStatError (/home/benjamin/workspace/AngularFun/node_modules/express/node_modules/send/lib/send.js:248:48)
    at /home/benjamin/workspace/AngularFun/node_modules/express/node_modules/send/lib/send.js:320:26
    at Object.oncomplete (fs.js:96:15)

**Comment by CaryLandholt** [comment]
Yeah, I've already logged an issue for this.
https://github.com/CaryLandholt/AngularFun/issues/49

I'm working on it.  :)

Sorry about that.

**Comment by beninfobelt** [comment]
Sounds good - the conversion from coffee script has been successful so it allows me to study the code in the meantime. Very interesting how you create a function, inject the function, and then .call(this) for each js file!

**Comment by CaryLandholt** [comment]
Upgraded ngShim
https://github.com/CaryLandholt/AngularFun/commit/394c8503d3fb687d58514ce0015fda03c43e6e07
