### ISSUE TITLE
npm install errors

### ISSUE THREAD

**Issue by 11111000000** [CaryLandholt/AngularFun#58]
1) pngquant should return path to pngquant binary:
     Uncaught AssertionError: false == true
      at /home/az/work/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin/test/test-path.js:17:4
      at ChildProcess.exithandler (child_process.js:641:7)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at maybeClose (child_process.js:735:16)
      at Socket.<anonymous> (child_process.js:948:11)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Pipe.close (net.js:466:12)

  2) pngquant should successfully proxy pngquant:
     Uncaught AssertionError: false == true
      at /home/az/work/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin/test/test-path.js:26:4
      at ChildProcess.exithandler (child_process.js:641:7)
      at ChildProcess.EventEmitter.emit (events.js:98:17)
      at maybeClose (child_process.js:735:16)
      at Socket.<anonymous> (child_process.js:948:11)
      at Socket.EventEmitter.emit (events.js:95:17)
      at Pipe.close (net.js:466:12)

  3) pngquant should minify a .png:
     Uncaught Error: ENOENT, no such file or directory 'test/fixtures/test-fs8.png'
      at Object.fs.statSync (fs.js:684:18)
      at /home/az/work/AngularFun/node_modules/grunt-contrib-imagemin/node_modules/pngquant-bin/test/test-path.js:38:20
      at ChildProcess.exithandler (child_process.js:641:7)

**Comment by 11111000000** [comment]
And then, after 'grunt dev', looks like something wrong with markup:

https://dl.dropboxusercontent.com/u/17582546/shots/255225418_full.png

node --version
v0.10.18

**Comment by CaryLandholt** [comment]
What OS are you using?
The screenshot actually looks right.

**Comment by 11111000000** [comment]
ok, I'm using Archlinux up to date

**Comment by CaryLandholt** [comment]
Looks like this is a known issue.
https://github.com/sindresorhus/node-pngquant-bin/issues/8

Try deleting the node_modules directory from the root of the project and then `npm install`

**Comment by CaryLandholt** [comment]
I'm seeing this error on a Windows 8 machine as well.
I'm not seeing it on my Mac, however.

Until the offending node module is fixed, we'll have to put up with the console errors.

I'll keep an eye out.

Thanks,
Cary
